### ISSUE TITLE
Crash loading DiscoScience and ToDo List (Factorio 0.18.21)

### ISSUE THREAD

**Issue by otobot1** [Rybadour/Foreman#32]
Foreman encountered an error while loading the Factorio data with these mods in the mods folder. I copied the text in the error popup unto errortext.txt and included the errorlog.txt from the Foreman folder. Interestingly, deactivating the mods and removing the .zips from my mods folder did not fix the problem.
[errorlog.txt](https://github.com/Rybadour/Foreman/files/4605634/errorlog.txt)
[errortext.txt](https://github.com/Rybadour/Foreman/files/4605635/errortext.txt)
[DiscoScience_1.0.2.zip](https://github.com/Rybadour/Foreman/files/4605637/DiscoScience_1.0.2.zip)
[Todo-List_18.0.1.zip](https://github.com/Rybadour/Foreman/files/4605638/Todo-List_18.0.1.zip)
[mod-list.txt](https://github.com/Rybadour/Foreman/files/4605641/mod-list.txt)

**Comment by Rybadour** [comment]
Might as ask which version of Foreman your using? The one referenced in the releases here on Github should not crash when mods have errors...

Btw: The root cause is that some of the files in the mod zip file have a "modified date" that is unparseable. I've switch us to using a better extraction library and the issue is now gone!

**Comment by otobot1** [comment]
Not sure where to find the version number, but I downloaded it from the top of the "Releases" page yesterday.

**Comment by Rybadour** [comment]
Alright! I'll want to double check why Foreman crashes for you it's probably because it's a release build but I'm not sure why it's different.

Anyways, I've fixed the issue. Since there's a bunch of other fixes as well I'll push out a new release :D
