### ISSUE TITLE
"Automatically create missing nodes" needs enhancements

### ISSUE THREAD

**Issue by Rybadour** [Rybadour/Foreman#7]
Creating input nodes automatically doesn't seem to work how user might expect. I'm not really sure how the algorithm works exactly so I'll outline my opinion of how the graph should be generated. It often stops generating randomly and generates duplicate nodes instead of linking them together.

Ideally, I think it should generate all recipes for all the inputs recursively. It should only stop generating at raw resources such as ore, oil, or water. All recipes should be linked to common nodes. Connection between nodes should avoid overlapping if at all possible.

**Comment by riking** [comment]
See also #29 - isolated sub-graphs that "Automtically create missing nodes" needs to recurse into.

**Comment by Rybadour** [comment]
Note there are some huge difficulties in generating a reason graph when dealing with the other complex mods. But also when dealing with items like light oil that have multiple different recipes.

Ideally, we should choose recipes based on the player's technology level but in the meantime the best we can do is choose the first one and make it easier to change the recipe.

**Comment by Rybadour** [comment]
Closing in favour of https://github.com/Rybadour/Foreman/issues/34
